"""
Django settings for luffycity project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f8(p@z808qrz5cj1i*gpipivrld1!!s53ax-cc30*35zg31iyw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'luffycity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'luffywebpack/dist')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luffycity.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "luffydb",
        "PORT":3306,
        "HOST":"127.0.0.1",
        'USER':"root",
        "PASSWORD":"123456789"
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

#vue前端
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'luffywebpack/dist/static')
]



REST_FRAMEWORK={
    'DEFAULT_AUTHENTICATION_CLASSES':[],
	'VERSION_PARAM':'version',  #版本 get形式的参数
	'ALLOWED_VERSIONS':['v1','v2'],   # 允许的版本
	'DEFAULT_VERSION':'v1',  #默认的版本
	'DEFAULT_VERSIONING_CLASS':'rest_framework.versioning.URLPathVersioning',
	# 'rest_framework.versioning.QueryParameterVersioning' # 源码里面只支持配置一种方式 ；通过什么方式结合的版本(参数或者是url)
    # "DEFAULT_PAGINATION_CLASS": 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 2,
}

# redis配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "PASSWORD": "zh4350697",
        }
    }
}

# shop_name = 'luffy_shopping_car_%s_%s' % (user_id, course_id)
#pay_name = "payment_%s_%s" % (user_id, key), v)
#global_coupon_name = "payment_global_coupon_%s" % (user_id)

SHOPPING_CRA_NAME = 'luffy_shopping_car_%s_%s'
PAYMENT_CRA_NAME = 'luffy_payment_%s_%s'
GLOBAL_COUPON= 'luffy_payment_global_coupon_%s'


# 支付相关配置
APPID = "2016101000655824"
NOTIFY_URL = "http://127.0.0.1:8008/api/v2/update_order/"
RETURN_URL = "http://127.0.0.1:8008/api/v2/pay_result/"
PRI_KEY_PATH = "keys/app_private_2048.txt"
PUB_KEY_PATH = "keys/alipay_public_2048.txt"